//this variable is an enumeration, hence the order matters
var CMD_ = {
	NONE:0,
//====================COMMON==============================
	GET_ID_EXISTS:0,

//====================APP==================================================
	SET_APP_ID:0,//broadcast
	SET_APP_CHANNEL_ID_FIRST:0,
	APP_CHANNEL_ADD:0,
	APP_CHANNEL_DELETE:0,
	APP_STEP_ADD:0,
	APP_STEP_DELETE:0,
	APP_RESET:0,

	SET_APP_SERIAL_RATE:0,
	SET_APP_SERIAL_CONFIG:0,
	SET_APP_SERIAL_KIND:0,

	GET_APP_VARIABLES:0,

	GET_APP_ID:0,//broadcast
	GET_APP_CHANNEL_ID_FIRST:0,
	GET_APP_STATE:0,
	GET_APP_ERROR:0,

	GET_APP_SERIAL_RATE:0,
	GET_APP_SERIAL_CONFIG:0,
	GET_APP_SERIAL_KIND:0,

//====================CHANNEL==================================================
	CHANNEL_START:0,
	CHANNEL_STOP:0,
	CHANNEL_RELOAD:0,

	SET_CHANNEL_ID:0,
	SET_CHANNEL_GOAL:0,

	SET_CHANNEL_SAVE_GOAL:0,
	GET_CHANNEL_SAVE_GOAL:0,
	GETR_CHANNEL_SAVE_GOAL:0,

	SET_CHANNEL_DEVICE_KIND:0,
	GET_CHANNEL_DEVICE_KIND:0,
	GETR_CHANNEL_DEVICE_KIND:0,
	
	SET_CHANNEL_PIN:0,
	GET_CHANNEL_PIN:0,
	GETR_CHANNEL_PIN:0,

	GET_CHANNEL_FTS:0,
	GET_CHANNEL_ID:0,
	GET_CHANNEL_GOAL:0,

	GETR_CHANNEL_STATE:0,
	GETR_CHANNEL_ERROR:0,
	GETR_CHANNEL_ENABLE:0,

	GETR_CHANNEL_GOAL:0,

//====================PWM==================================================
	SET_PWM_RESOLUTION:0,
	SET_PWM_PERIOD:0,
	SET_PWM_PW_MIN:0,
	SET_PWM_PW_MAX:0,

	GET_PWM_RESOLUTION:0,
	GET_PWM_PERIOD:0,
	GET_PWM_PW_MIN:0,
	GET_PWM_PW_MAX:0,

	GETR_PWM_RESOLUTION:0,
	GETR_PWM_PERIOD:0,
	GETR_PWM_PW_MIN:0,
	GETR_PWM_PW_MAX:0,

//====================REG==================================================
	SET_POS2_HYS:0,
	SET_POS2_OUT_MIN:0,
	SET_POS2_OUT_MAX:0,
	SET_POS2_MODE:0,

	SET_PID_KP:0,
	SET_PID_KI:0,
	SET_PID_KD:0,
	SET_PID_OUT_MIN:0,
	SET_PID_OUT_MAX:0,
	SET_PID_MODE:0,

	SET_REG_METHOD:0,


	GET_POS2_HYS:0,
	GET_POS2_OUT_MIN:0,
	GET_POS2_OUT_MAX:0,
	GET_POS2_MODE:0,

	GET_PID_KP:0,
	GET_PID_KI:0,
	GET_PID_KD:0,
	GET_PID_OUT_MIN:0,
	GET_PID_OUT_MAX:0,
	GET_PID_MODE:0,

	GET_REG_METHOD:0,

	GETR_POS2_HYS:0,
	GETR_POS2_OUT_MIN:0,
	GETR_POS2_OUT_MAX:0,
	GETR_POS2_MODE:0,

	GETR_PID_KP:0,
	GETR_PID_KI:0,
	GETR_PID_KD:0,
	GETR_PID_OUT_MIN:0,
	GETR_PID_OUT_MAX:0,
	GETR_PID_MODE:0,

	GETR_REG_METHOD:0,

//====================REMOTE==================================================
	SET_REM_ID:0,
	SET_REM_INTERVAL:0,
	SET_REM_SERIAL:0,

	SET_RSENSOR_ID:0,
	SET_RSENSOR_INTERVAL:0,
	SET_RSENSOR_SERIAL:0,

	GET_REM_ID:0,
	GET_REM_INTERVAL:0,
	GET_REM_SERIAL:0,

	GET_RSENSOR_ID:0,
	GET_RSENSOR_INTERVAL:0,
	GET_RSENSOR_SERIAL:0,

	GETR_REM_ID:0,
	GETR_REM_INTERVAL:0,
	GETR_REM_SERIAL:0,
	GETR_REM_STATE:0,
	GETR_REM_ERROR:0,

	GETR_RSENSOR_ID:0,
	GETR_RSENSOR_INTERVAL:0,
	GETR_RSENSOR_SERIAL:0,
	GETR_RSENSOR_STATE:0,
	GETR_RSENSOR_ERROR:0,

//====================RTC==================================================
	SET_RTC_DATE:0,
	SET_RTC_TIME:0,
	GET_RTC_DATE:0,
	GET_RTC_TIME:0,

//====================SECURE==================================================
	SET_SEC_ENABLE:0,
	SET_SEC_TM:0,
	SET_SEC_OUT:0,

	GET_SEC_ENABLE:0,
	GET_SEC_TM:0,
	GET_SEC_OUT:0,

	GETR_SEC_ENABLE:0,
	GETR_SEC_TM:0,
	GETR_SEC_OUT:0,
	GETR_SEC_STATE:0,

//====================SERVO==================================================
	SET_SERVO_PW_MIN:0,
	SET_SERVO_PW_MAX:0,
	SET_SERVO_IN_MIN:0,
	SET_SERVO_IN_MAX:0,

	GET_SERVO_PW_MIN:0,
	GET_SERVO_PW_MAX:0,
	GET_SERVO_IN_MIN:0,
	GET_SERVO_IN_MAX:0,

	GETR_SERVO_PW_MIN:0,
	GETR_SERVO_PW_MAX:0,
	GETR_SERVO_IN_MIN:0,
	GETR_SERVO_IN_MAX:0,

//====================TIMER==================================================
	SET_TIMER_TIME_ON:0,
	SET_TIMER_TIME_OFF:0,
	SET_TIMER_OUTPUT_ON:0,
	SET_TIMER_OUTPUT_OFF:0,
	SET_TIMER_INTERVAL_ON:0,
	SET_TIMER_INTERVAL_OFF:0,

	GET_TIMER_TIME_ON:0,
	GET_TIMER_TIME_OFF:0,
	GET_TIMER_OUTPUT_ON:0,
	GET_TIMER_OUTPUT_OFF:0,
	GET_TIMER_INTERVAL_ON:0,
	GET_TIMER_INTERVAL_OFF:0,

	GETR_TIMER_TIME_ON:0,
	GETR_TIMER_TIME_OFF:0,
	GETR_TIMER_OUTPUT_ON:0,
	GETR_TIMER_OUTPUT_OFF:0,
	GETR_TIMER_INTERVAL_ON:0,
	GETR_TIMER_INTERVAL_OFF:0,
	
	CMD_GATEWAY_PRINT:0,
	CMD_GATEWAY_RESET:0
};
