
let aoid_description_dict = [
	{id: AOID_DESCRIPTION_UNKNOWN, str: ["unknown", "неизвестно"]},
	{id: AOID_DESCRIPTION_APP, str: ["application", "приложение"]},
	{id: AOID_DESCRIPTION_START, str: ["start", "старт"]},
	{id: AOID_DESCRIPTION_STOP, str: ["stop", "стоп"]},
	{id: AOID_DESCRIPTION_RESET, str: ["reset", "сброс"]},
	{id: AOID_DESCRIPTION_ID, str: ["ID", "идентификатор"]},
	{id: AOID_DESCRIPTION_DEVICE_KIND, str: ["device kind", "тип устройства"]},
	{id: AOID_DESCRIPTION_SERIALS, str: ["serial ports", "последовательные порты"]},
	{id: AOID_DESCRIPTION_SERIAL, str: ["serial port", "последовательный порт"]},
	{id: AOID_DESCRIPTION_CHANNELS, str: ["channels", "каналы"]},
	{id: AOID_DESCRIPTION_CHANNEL, str: ["channel", "канал"]},
	{id: AOID_DESCRIPTION_REMOTE_ID, str: ["remote ID", "удаленный идентификатор"]},
	{id: AOID_DESCRIPTION_RATE, str: ["rate", "скорость"]},
	{id: AOID_DESCRIPTION_DPS, str: ["DPS", "DPS"]},
	{id: AOID_DESCRIPTION_TIME, str: ["time", "время"]},
	{id: AOID_DESCRIPTION_MODE, str: ["mode", "режим"]},
	{id: AOID_DESCRIPTION_NOID_FIRST, str: ["Noid first", "СИД первый"]},
	{id: AOID_DESCRIPTION_NOID_NEXT, str: ["Noid next", "СИД следующий"]},
	{id: AOID_DESCRIPTION_ENABLE, str: ["enable", "активировать"]},
	{id: AOID_DESCRIPTION_TIMEOUT, str: ["timeout", "время"]},
	{id: AOID_DESCRIPTION_OUTPUT, str: ["output", "выход"]},
	{id: AOID_DESCRIPTION_SECURE, str: ["secure", "безопасность"]},
	{id: AOID_DESCRIPTION_SPWM, str: ["software PWM", "программный ШИМ"]},
	{id: AOID_DESCRIPTION_HPWM, str: ["hardware PWM", "аппаратный ШИМ"]},
	{id: AOID_DESCRIPTION_RESOLUTION, str: ["resolution", "разрешение"]},
	{id: AOID_DESCRIPTION_PERIOD_MS, str: ["period, ms", "период, мс"]},
	{id: AOID_DESCRIPTION_DUTY_CYCLE_MIN_MS, str: ["duty cycle min, ms", "минимальная скважность, мс"]},
	{id: AOID_DESCRIPTION_DUTY_CYCLE_MAX_MS, str: ["duty cycle max, ms", "максимальная скважность, мс"]},
	{id: AOID_DESCRIPTION_PULSE_WIDTH_MIN_US, str: ["pulse width min, us", "минимальная ширина импульса, мкс"]},
	{id: AOID_DESCRIPTION_PULSE_WIDTH_MAX_US, str: ["pulse width max, us", "максимальная ширина импульса, мкс"]},
	{id: AOID_DESCRIPTION_INPUT_MIN, str: ["input min", "минимальный вход"]},
	{id: AOID_DESCRIPTION_INPUT_MAX, str: ["input max", "максимальный вход"]},
	{id: AOID_DESCRIPTION_PIN, str: ["pin", "ножка"]},
	{id: AOID_DESCRIPTION_POLL_INTERVAL_MS, str: ["poll interval, ms", "период опроса, мс"]},
	{id: AOID_DESCRIPTION_PIN_CS, str: ["CS pin", "ножка CS"]},
	{id: AOID_DESCRIPTION_PIN_SCLK, str: ["SCLK pin", "ножка SCLK"]},
	{id: AOID_DESCRIPTION_PIN_MISO, str: ["MISO pin", "ножка MISO"]},
	{id: AOID_DESCRIPTION_PIN_MOSI, str: ["MOSI pin", "ножка MOSI"]},
	{id: AOID_DESCRIPTION_DAY_TIMER, str: ["day timer", "суточный таймер"]},
	{id: AOID_DESCRIPTION_ON_TIME, str: ["on time", "время включения"]},
	{id: AOID_DESCRIPTION_OFF_TIME, str: ["off time", "время выключения"]},
	{id: AOID_DESCRIPTION_2STATE_CYCLIC_TIMER, str: ["2-state cyclic timer", "циклический таймер с двумя состояниями"]},
	{id: AOID_DESCRIPTION_INTERVAL1_S, str: ["interval 1, s", "продолжительность 1, с"]},
	{id: AOID_DESCRIPTION_INTERVAL2_S, str: ["interval 2, s", "продолжительность 2, с"]},
	{id: AOID_DESCRIPTION_INITIAL_PIN_STATE, str: ["initial pin state", "начальное состояние ножки"]},
	{id: AOID_DESCRIPTION_DATE, str: ["date", "дата"]},
	{id: AOID_DESCRIPTION_RTC, str: ["RTC", "часы реального времени"]},
	{id: AOID_DESCRIPTION_1WIRE, str: ["1-Wire", "1-Wire"]},
	{id: AOID_DESCRIPTION_ADDRESS, str: ["address", "адрес"]},
	{id: AOID_DESCRIPTION_ADDRESS_READ, str: ["read address", "прочитать адрес"]},
	{id: AOID_DESCRIPTION_1WIRES, str: ["1-Wire buses", "шины 1-Wire"]},
	{id: AOID_DESCRIPTION_DEVICE, str: ["device", "устройство"]},
	{id: AOID_DESCRIPTION_DEVICES, str: ["devices", "устройства"]},
	{id: AOID_DESCRIPTION_PIN1, str: ["pin 1", "ножка 1"]},
	{id: AOID_DESCRIPTION_PIN2, str: ["pin 2", "ножка 2"]},
	{id: AOID_DESCRIPTION_PIN3, str: ["pin 3", "ножка 3"]},
	{id: AOID_DESCRIPTION_DISPLAY, str: ["display", "дисплей"]},
	{id: AOID_DESCRIPTION_PRECISION, str: ["precision", "точность"]},
	{id: AOID_DESCRIPTION_NOID_COMMAND, str: ["NOID command", "команда сетевого объекта"]},
	{id: AOID_DESCRIPTION_SERIAL_ID, str: ["serial ID", "идентификатор последовательного порта"]},
	{id: AOID_DESCRIPTION_TIMEUS, str: ["time, us", "время, мкс"]},
	{id: AOID_DESCRIPTION_TIMEMS, str: ["time, ms", "время, мс"]},
	{id: AOID_DESCRIPTION_TIMES, str: ["time, s", "время, с"]}
];

let aoid_command_dict = [
	{id: CMD_AOID_SET_RAM_VALUE, str: ["set parameter value to RAM", "установить значение параметра в ПЗУ"]},
	{id: CMD_AOID_SET_NVRAM_VALUE, str: ["set parameter value to NVRAM", "установить значение параметра в ПЗУ"]},
	{id: CMD_AOID_GET_RAM_VALUE, str: ["get parameter value from RAM", "получить значение параметра из ОЗУ"]},
	{id: CMD_AOID_GET_NVRAM_VALUE, str: ["get parameter value from NVRAM", "получить значение параметра из ПЗУ"]},
	{id: CMD_AOID_DELETE, str: ["delete", "удалить"]},
	{id: CMD_AOID_ADD, str: ["add", "добавить"]},
	{id: CMD_AOID_START, str: ["start", "старт"]},
	{id: CMD_AOID_STOP, str: ["stop", "стоп"]},
	{id: CMD_AOID_RESET, str: ["reset", "сброс"]}
];
