trans.addDict([
    {id: 0, str: ["back", "назад"]},
    {id: 1, str: ["save", "сохранить"]},
    {id: 2, str: ["apply", "принять"]},
    {id: 3, str: ["change", "заменить"]},
    {id: 4, str: ["toggle", "переключить"]},
    {id: 5, str: ["cancel", "отменить"]},
    {id: 6, str: ["copy", "копир"]},
    {id: 7, str: ["paste", "встав"]},
    {id: 8, str: ["january", "январь"]},
    {id: 9, str: ["february", "февраль"]},
    {id: 10, str: ["march", "март"]},
    {id: 11, str: ["april", "апрель"]},
    {id: 12, str: ["may", "май"]},
    {id: 13, str: ["june", "июнь"]},
    {id: 14, str: ["july", "июль"]},
    {id: 15, str: ["august", "август"]},
    {id: 16, str: ["september", "сентябрь"]},
    {id: 17, str: ["october", "октябрь"]},
    {id: 18, str: ["november", "ноябрь"]},
    {id: 19, str: ["december", "декабрь"]},
    {id: 20, str: ["jan", "янв"]},
    {id: 21, str: ["feb", "фев"]},
    {id: 22, str: ["mar", "мар"]},
    {id: 23, str: ["apr", "апр"]},
    {id: 24, str: ["may", "май"]},
    {id: 25, str: ["jun", "июн"]},
    {id: 26, str: ["jul", "июл"]},
    {id: 27, str: ["aug", "авг"]},
    {id: 28, str: ["sep", "сен"]},
    {id: 29, str: ["oct", "окт"]},
    {id: 30, str: ["nov", "ноя"]},
    {id: 31, str: ["dec", "дек"]},
    {id: 32, str: ["monday", "понедельник"]},
    {id: 33, str: ["tuesday", "вторник"]},
    {id: 34, str: ["wednesday", "среда"]},
    {id: 35, str: ["thursday", "четверг"]},
    {id: 36, str: ["friday", "пятница"]},
    {id: 37, str: ["saturday", "суббота"]},
    {id: 38, str: ["sunday", "воскресенье"]},
    {id: 39, str: ["mo", "пн"]},
    {id: 40, str: ["tu", "вт"]},
    {id: 41, str: ["we", "ср"]},
    {id: 42, str: ["th", "чт"]},
    {id: 43, str: ["fr", "пт"]},
    {id: 44, str: ["sa", "сб"]},
    {id: 45, str: ["su", "вс"]},
    {id: 46, str: ["update", "обновить"]},
    {id: 48, str: ["yes", "да"]},
    {id: 49, str: ["no", "нет"]},
    {id: 50, str: ["add", "добавить"]},
    {id: 51, str: ["delete", "удалить"]},
    {id: 52, str: ["year", "год"]},
    {id: 53, str: ["weekday", "день недели"]},
    {id: 54, str: ["month day time", "месяц день время"]},
    {id: 55, str: ["time and date settings", "настройки даты и времени"]},
    {id: 56, str: ["sort", "сортировка"]},
    {id: 57, str: ["download", "загрузить"]},
    {id: 58, str: ["error", "ошибка"]},
    {id: 59, str: ["warning", "предупреждение"]},
    {id: 60, str: ["notification", "уведомление"]},
	{id: 61, str: ["settings", "настройки"]},
	{id: 62, str: ["open", "открыть"]},
	{id: 63, str: ["close", "закрыть"]},
	{id: 64, str: ["password", "пароль"]},
	{id: 65, str: ["authorization", "авторизация"]},
	{id: 66, str: ["login", "вход"]},
	{id: 67, str: ["logout", "выход"]},
	{id: 68, str: ["day", "сутки"]},
	{id: 69, str: ["week", "неделя"]},
	{id: 70, str: ["month", "месяц"]},
	{id: 71, str: ["turn on", "включить"]},
	{id: 72, str: ["turn off", "выключить"]},
		
    {id: 200, str: ["success", "успешно"]},
    {id: 201, str: ["fail", "неудачно"]},
    {id: 202, str: ["update failed", "не удалось обновить"]},
    {id: 203, str: ["toggle failed", "не удалось переключить"]},
    {id: 204, str: ["save failed", "не удалось сохранить"]},
    {id: 205, str: ["duplicate key", "дублирование ключа"]}
]);

//string_smp
trans.addDict([
    {id: 206, str: ["too long string", "слишком длинная строка"]},
    {id: 207, str: ["bad character found", "найден недопустимый символ"]},
    
]);

